version: '3.7'
services:
  gogindddcqrs-postgres:
    image: postgres:latest
    container_name: gogindddcqrs-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gogindddcqrs
    ports:
      - "5432:5432"
    volumes:
      - gogindddcqrs-postgres:/var/lib/postgresql/data
    networks:
      - gogindddcqrs-network

  gogindddcqrs-redis:
    image: "redis:alpine"
    container_name: gogindddcqrs-redis
    ports:
      - "6379:6379"
    command: >
      --requirepass redis
volumes:
  gogindddcqrs-postgres:

# Networks to be created to facilitate communication between containers
networks:
  gogindddcqrs-network:
    driver: bridge
